# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    env:
      #NUGET_TOKEN: ${{secrets.GITHUB_TOKEN}}
      NUGET_TOKEN: ${{secrets.GHP_RW}}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1'
          source-url: https://nuget.pkg.github.com/mmulhearn/index.json
        env:
          NUGET_AUTH_TOKEN: ${{env.NUGET_TOKEN}}

      - name: nuget sources
        run: |
          cat ../nuget.config || echo no nuget.config
          
      - name: Build
        run: dotnet build -c Release
